

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


# Load necessary packages
library(ggplot2)
library(rmarkdown)
library(dplyr)
library(sjPlot)

```

```{r}

# --- Import the Eye Tracking Data ---

eyetracking_data <- read.csv("YOUR_PATH/EyeTrackingData_T2.csv")

# --- Prepare the Data for Statistical Analysis ---

# 1. Remove trials containing Na

eyetracking_data <- na.omit(eyetracking_data)

```

```{r}

# --- Create the Probability Plot ---

# count first fixations in all combinations of valence_looked, side_looked, and arousal_difference
et_data_probabilities <- eyetracking_data %>%
  
  # picture_pos relates to picture positioning of the valenced images
  # picture_pos = True: negative image was on the left and positive image on the right side
  # picture_pos = False: positive image was on the left and negative image on the right side
  mutate(picture_pos = (valence_looked == side_looked)) %>% 
  # group trials with same picture positioning and same arousal_differences and count them
  group_by(valence_looked, picture_pos, arousal_difference) %>% 
  summarise(fixation_count = n(), .groups = 'drop')


# create a new column to count how many trials with the same composition there were
et_data_probabilities$total_trials <- NA

### CONTEXT:
# since trials with same picture position but reversed arousal_difference and reversed valence_looked relate to similar trial compositions they are added together to derive total_trials
# e.g., composition: negative left, positive right, negative more arousing by 2 than the positive image
# in this example the first fixation could have gone to the negative image (side_looked = left, valence_looked = negative, arousal_difference = +2) or to the positive image (side_looked = right, valence_looked = positive, arousal_difference = -2)
# total_trials therefore counts how many trials had these similar compositions so that probabilities can be computed

# go through each trial
for (i in 1:nrow(et_data_probabilities)) {
  
  # get the current valence_looked, arousal_difference, and picture_position
  valence <- et_data_probabilities$valence_looked[i]
  arousal_diff <- et_data_probabilities$arousal_difference[i]
  pic_pos <- et_data_probabilities$picture_pos[i]
  
  # calculate the reversed valence and arousal_difference
  reversed_valence <- ifelse(valence == 0, 1, 0)
  reversed_arousal <- -arousal_diff
  
  # get the corresponding row with the reversed valence and arousal_difference since it relates to the same trial composition
  reversed_row_index <- which(et_data_probabilities$valence_looked == reversed_valence & et_data_probabilities$arousal_difference == reversed_arousal & et_data_probabilities$picture_pos == pic_pos)
  
  # get the fixation_count from the corresponding row
  if (length(reversed_row_index) > 0) {
    reversed_fixation_count <- et_data_probabilities$fixation_count[reversed_row_index]
    
  # if there exists no corresponding row just take 0 as fixation_count
  } else {
    reversed_fixation_count <- 0
  }
  
  # add the fixations from corresponding rows together in total_trials to count how many trials had same composition
  et_data_probabilities$total_trials[i] <- et_data_probabilities$fixation_count[i] + reversed_fixation_count
}

# add probabilities to the data frame and add type for the plot
et_data_probabilities <- et_data_probabilities %>%
  # compute the probabilities based on fixation_counts and total_trials
  mutate(probability = fixation_count / total_trials) %>%
  # create type which considers where the first fixation went and what the picture positioning was
  mutate(type = paste(picture_pos, valence_looked, sep = "_")) %>%
  mutate(type = recode(type,
                       "FALSE_0" = "negative, right side",
                       "FALSE_1" = "positive, left side",
                       "TRUE_0" = "negative, left side",
                       "TRUE_1" = "positive, right side"))

# generate the probability plot
ggplot(et_data_probabilities, aes(x = arousal_difference, y = probability, color = factor(type), group = type)) +
  geom_point(size = 3, alpha = 0.7) +  
  geom_line(size = 1) +  
  labs(x = "Arousal-Difference",
       y = "Probability",
       color = "First Fixated Image") + 
  scale_color_manual(values = c("positive, left side" = "darkgreen", "positive, right side" = "lightgreen", "negative, left side" = "red4", "negative, right side" = "brown3")) +
  theme_minimal()

```

```{r}

# --- Get the Counts for First Fixation Allocations ---

# create data frame that contains information about how many trials there were for each trial composition and how many first fixations went to which image
table_data <- et_data_probabilities %>%
  dplyr::select(-c(picture_pos, probability, valence_looked)) %>%
  filter(type != "positive, left side") %>%
  filter(type != "positive, right side") %>%
  mutate(positive_FF = total_trials - fixation_count) %>%
  rename(negative_FF = fixation_count) %>%
  dplyr::select(arousal_difference, positive_FF, negative_FF, total_trials, type)


# get the data for trials in which the positive image was left and the negative image right 
ff_positive_left <- table_data %>%
  filter(type == "negative, right side") %>%
  dplyr::select(-type)

# get the data for trials in which the negative image was left and the positive image right
ff_positive_right <- table_data %>%
  filter(type == "negative, left side") %>%
  dplyr::select(-type)

# print the tables
print(ff_positive_left)
print(ff_positive_right)

```

