---
title: "ET_RT_effect_coding"
output: html_document
date: "2025-04-05"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# --- Import the Packages ---

library(lme4)
library(lmerTest)  
library(lmtest)
library(rmarkdown)
library(dplyr)
library(MASS)
library(ggplot2)
library(sjPlot)
library(ggeffects)
library(effectsize)
library(car)

```

```{r}

# --- Functions ---

# function to create a residual plot for a model
plot_residuals <- function(model, data, dependent_var, model_name) {
  df_res <- data.frame(
    Actual = data[[dependent_var]],       
    Fitted = fitted(model),              
    Residuals = resid(model),            
    Std_Residuals = residuals(model, type = "pearson") 
  )
  

  ggplot(df_res, aes(x = Fitted, y = Std_Residuals)) +
    geom_point(alpha = 0.5, color = "darkgreen") +
    geom_hline(yintercept = 0, linetype = "dashed") +
    labs(title = "Standardized Residuals vs Predicted Values for the LMM",
         subtitle = sprintf("%s", model_name),
         x = "Predicted values",
         y = "Standardized Residuals") +
    theme_minimal() +
    theme(plot.subtitle = element_text(color = "grey35"))
    
}

```

```{r}

# --- Import the Eye Tracking Data ---

eyetracking_data <- read.csv("C:/Users/FABI/Documents/Osnabrück - Cognitive Science/Bachelor/Analysis/Data/preprocessed Data/EyeTrackingData_T2.csv")

# --- Prepare the Data for Statistical Analysis ---

# 1. Remove trials containing Na

eyetracking_data <- na.omit(eyetracking_data)

# 2. set variables to correct data types

# factors
# valence_looked: 0 is negative, 1 is positive
# side_looked: 0 is left, 1 is right
eyetracking_data$valence_looked <- factor(eyetracking_data$valence_looked)
eyetracking_data$side_looked <- factor(eyetracking_data$side_looked)
eyetracking_data$participant_id <- factor(eyetracking_data$participant_id)
eyetracking_data$picture_looked <- factor(eyetracking_data$picture_looked)

# numeric
eyetracking_data$arousal_difference <- as.numeric(eyetracking_data$arousal_difference)
eyetracking_data$arousal_looked <- as.numeric(eyetracking_data$arousal_looked)

#adjust the order of levels
eyetracking_data$valence_looked <- factor(eyetracking_data$valence_looked, levels = c("1", "0"))
eyetracking_data$side_looked <- factor(eyetracking_data$side_looked, levels = c("1", "0"))

# 3. for Valence and Side introduce Effect Coding

contrasts(eyetracking_data$valence_looked) <- contr.sum(levels(eyetracking_data$valence_looked))
contrasts(eyetracking_data$side_looked) <- contr.sum(levels(eyetracking_data$side_looked))

```

```{r}

# --- Create a QQ-Plot ---

# QQ-plots to check the normality of the eye tracking data
qqnorm(eyetracking_data$log.transformed.rt, main = "Q-Q Plot of logRT from the Eye Tracking Data")
qqline(eyetracking_data$log.transformed.rt)

```

```{r}

# --- Statistical Analysis ---

# apply the LMM on the eye tracking data
model_ET <- lmer(log.transformed.rt ~ valence_looked * arousal_difference + side_looked + (1 | participant_id), 
                   data = eyetracking_data, REML = TRUE)

# get the model summary
summary(model_ET)

# print the residuals of the model
plot_residuals(model_ET, data = eyetracking_data, dependent_var = "log.transformed.rt", "ET logRT ~ Valence * Arousal-Difference + Side + (1|participant)")

```

```{r}

# --- Interpretation of the Coefficients ---

# get the coefficients
betas <- summary(model_ET)$coefficients[, 1]

# converting coefficients into interpretable reaction time information 
cat(paste("Comparison Side: ", 10^(2*betas["side_looked1"]), "Percent: ", ((1-(10^(2*betas["side_looked1"])))*100)*(-1), "%", " \n"))

```

```{r}

# --- Interpretation of the Interaction ---

# get model prediction for the interaction
pred_interaction_et <- ggpredict(model_ET, terms = c("arousal_difference", "valence_looked"))


# plotting the interaction effects
et_interaction_plot <- plot(pred_interaction_et, show_ci = FALSE) +
  geom_line(aes(color = group)) +
  scale_color_manual(values = c("1" = "green3", "0" = "red2"),
                     labels = c("1" = "positive", "0" = "negative"),
                     name = "Valence") +
  labs(title = ' ', x = "Arousal-Difference", y = "Predicted logRT") +
  theme_minimal() +
   theme(
    axis.title = element_text(size = 14),
    axis.text = element_text(size = 12),
    legend.title = element_text(size = 14),
    legend.text = element_text(size = 12)
  )

print(et_interaction_plot)


# turn model predictions of the interaction into a data frame
interaction_effect_df <- as.data.frame(pred_interaction_et)

# split up the predicitons for positive and negative Valence
positive_valence <- subset(interaction_effect_df, group == "1")
negative_valence <- subset(interaction_effect_df, group == "0")

# check how much the line increases / decreases for one Arousal-Difference unit
positive_slope <- diff(c(positive_valence$predicted[positive_valence$x == 2], positive_valence$predicted[positive_valence$x == 3]))

negative_slope <- diff(c(negative_valence$predicted[negative_valence$x == 2], negative_valence$predicted[negative_valence$x == 3]))


# print the slopes and their translation into reaction times
cat(paste("\n Interaction Slopes:\n", "  positive Valence: ", positive_slope, "\n   negative Valence: ", negative_slope))
cat(paste("\n Translation into RTs:\n", "  positive Valence: ", format(10^positive_slope, digits = 8), "\n   negative Valence: ", format(10^negative_slope, digits = 8)))


```

```{r}

# calculation of the effect sizes using partial eta squared
eta_squared(model_ET, partial = TRUE, ci=0.95, alternative = "two.sided")

```
